# Generated by Django 3.1.4 on 2020-12-09 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('flag', models.CharField(choices=[('VISA', 'Visa'), ('HIPER', 'Hipercard'), ('SANTANDER', 'Santander'), ('MASTERCARD', 'MasterCard'), ('ELO', 'Elo'), ('NUBANK', 'Nubank'), ('INTER', 'Inter')], max_length=255, verbose_name='Bandeira')),
                ('category', models.CharField(choices=[('DEBIT', 'Débito'), ('CREDIT', 'Crédito'), ('BOTH', 'Débito e Crédito')], max_length=255, verbose_name='Categoria')),
                ('last_numbers', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Últimos 4 números')),
                ('closing_day', models.IntegerField(verbose_name='Dia fechamento')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Propietário')),
            ],
            options={
                'verbose_name': 'Cartão',
                'verbose_name_plural': 'Cartões',
            },
        ),
    ]
